echo "Testing grants"
docker exec mysql-testing mysql -u root --password=example -e "select distinct grantee from information_schema.user_privileges;"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dking'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dking'@'localhost';"
echo "Staging grants"
docker exec mysql-staging mysql -u root --password=example -e "select distinct grantee from information_schema.user_privileges;"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dking'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dking'@'localhost';"
echo "Production grants"
docker exec mysql-production mysql -u root --password=example -e "select distinct grantee from information_schema.user_privileges;"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'duffyboy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dgilroy'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'dking'@'localhost';"
docker exec mysql-testing mysql -u root --password=example -e "DROP USER 'dking'@'localhost';"