---
- debug:
    var: username
- debug:
    var: password
- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    login_user: root
    login_password: example
    name: "{{ username }}"
    password: "{{ password }}"
    priv: '*.*:ALL,GRANT'
    state: present